query_dict = {
    "Paper Title": "Give the name of this document",
    "Author(s)": "Give the full names of the authors of this paper",
    "Author Email(s)": "If published, give the email adresses of the authors. If not, display N/A",
    "Year Published": "Give the year the paper was published",
    "Classification Performance": "If classification was used, give the numeric value of the classification performance. If not used, give N/A",
    "Regression Performance": "If regression was used, give the numeric value of the regression performance. If not used, give N/A",
    "Metric": "Give comma delimited list of performance metrics. This could be Accuracy, R2 score, ROCAUC score, etc",
    "Real-time Decoding": "Give Yes if real time decoding is used. Give No if not",
    "Motion Specificity": "Give a comma delimited list of the motions used. E.g. finger movements, grasp movements, wrist movements, finger & grasp movements, finger & wrist movements, grasp & wrist",
    "Dataset Available": "Give 'No' if no dataset if available. If there is a dataset available, give 'Yes: [link to dataset]'",
    "DAQ System": "Give the data aquisition system used to collect the signals",
    "Number of Channels": "Give the number of channels used to collect data",
    "Sampling Rate": "Give the numeric sampling rate. This is typically given in Hz or SPS",
    "Electrode Placement": "Give the location of the electrodes",
    "Number of Subjects": "Give the number of test subjects used",
    "Number of Trials": "Give the number of trials per subject",
    "Subject Include Amputees": "Give 'Yes' if study includes amputees. Give 'No' if it does not",
}